Komp 46 Radioknapp
kartverket/kvib pull request #237
Opened 2023-05-23 07:41 UTC by SebastianPMaro

# Beskrivelse

Fikset story for den midlertidige default Chakra radioknappen.
![image](https://github.com/kartverket/kvib/assets/122277136/446b728f-962f-4c4f-b742-d85059926c60)

# Sjekkliste

- [ ] Sjekket at komponenten matcher designet i Figma
- [ ] Har fått design review med en designer
- [ ] Sjekket universell utforming for komponenten. Se for eksempel:
  - https://www.magentaa11y.com/web/
  - https://a11y-101.com/development
  - https://www.a11yproject.com/checklist/#appearance
- [ ] Denne PR-en inneholder en enkelt komponent

2023-05-23 07:42 UTC, SebastianPMaro commented
Den har ingen egen styling, bare borderRadius=50% for å få den rund

2023-05-23 07:47 UTC, SebastianPMaro commented
Build kjører grønt lokalt (npm run build), så jeg vet ikke hva Github snakker om 😕

2023-05-23 12:56 UTC, annalytic commented on apps/storybook/stories/components/Radio/Radio.stories.tsx
> +      description: "Size of button",
Burde kanskje stå radio button istedenfor button i alle descriptions.

2023-05-23 12:56 UTC, annalytic commented on apps/storybook/stories/components/Radio/Radio.stories.tsx
> +  render: (args) => <KvibRadio children={"Klikk her"} {...args} />,
Fjern krøllparentes rundt {"Klikk her"}

2023-05-23 13:00 UTC, annalytic commented on apps/storybook/stories/components/Radio/Radio.stories.tsx
> +  title: "Komponenter/Knapper og lenker/Radio",
Radio burde legges under "Skjema".
Endre tittel til: "Komponenter/Skjema/Radio"

2023-05-23 13:09 UTC, annalytic commented
> Den har ingen egen styling, bare borderRadius=50% for å få den rund

Denne gjør ingenting så kan fjernes.

2023-05-23 13:13 UTC, SebastianPMaro commented
> > Den har ingen egen styling, bare borderRadius=50% for å få den rund
> 
> Denne gjør ingenting så kan fjernes.

Radioknappen var firkantet før det, kanskje noe ble ødelagt med designtokensa?

2023-05-23 13:16 UTC, annalytic commented on packages/react/src/radio/Radio.tsx
> +import { forwardRef, Radio as ChakraRadio, RadioProps as ChakraRadioProps } from "@chakra-ui/react";
Jeg ville kanskje ha flytta Radio under /forms

2023-05-23 13:22 UTC, annalytic commented on packages/react/src/radio/Radio.tsx
> +  size?: "sm" | "md" | "lg";
Du kan egentlig fjerne size her, og size, isDisabled fra linje 10, 15 og 17, da det default oppførsel i radio. Props du ikke ønsker å overskrive arves og videreføres automatisk gjennom props, så du trenger ikke sette dem eksplisitt.

2023-05-23 13:23 UTC, annalytic commented
> 

Jepp det var helt sikkert det 😅 Men nå skal alt være som det skal 😊

2023-05-24 09:39 UTC, annalytic requested changes
Noen kommentarer her og der. Men ellers ser det veldig bra ut! 💯 👍

Tips: Kan være lurt å "resolve conflicts" når endringene er utført og pushet til branch slik at den som reviewer vet at det er fikset ;)

2023-06-01 12:29 UTC, annalytic approved these changes
Supert jobba! 👏

2023-06-01 12:29 UTC, annalytic approved these changes
La inn to siste kommentarer. Etter de er fiksa er det bare å merge! Supert jobba! 👏 

NB!! Ikke glem å legge til changeset. Kjør `npx changeset` fra rot. Velg minor update og legg til beskrivelse på hva som er gjort. Noen minutter etter at branchen er merget inn vil det automatisk dukke opp en `Version packages` PR som du godkjenner selv og merger selv etter å ha sett over. Når denne er merget inn vil det dukke opp ny release under "Releases" i kvib-repoet. Det kan ta litt lenger tid før releasen dukker opp på https://www.npmjs.com/package/@kvib/react

2023-06-01 13:01 UTC, SebastianPMaro commented on packages/react/src/theme/components/radio.ts
> +    fontStyle: "normal",
Det er morsomt at du sier, forid jeg har ikke noe radio.ts fil på branchen min. Jeg slettet den fordi denne versjonen skulle være uten styling. jeg har pushet alt

2023-06-02 06:20 UTC, SebastianPMaro commented
> Når jeg tenker over det er det kanskje bedre du putter Radio.tsx og RadioGroup.tsx under `packages/react/src/forms/Radio.tsx`og `packages/react/src/forms/RadioGroup.tsx`.
> 
> Storyene kan du også plassere under `apps/storybook/stories/components/forms/Radio/` altså `apps/storybook/stories/components/forms/Radio/Radio.mdx` og `apps/storybook/stories/components/forms/Radio/Radio.stories.tsx`

samtidig som vi drev på med QA så ble jeg egentlig ferdig med stylet radioknapp, så skal jeg bare droppe denne og QA den andre eller pushe denne først?

2023-06-02 06:40 UTC, SebastianPMaro commented
nå som jeg tenker over det så har jeg allerede changeseta og alt så jeg bare merger denne og starter QA på den andre.

2023-06-02 06:41 UTC, merged