Komp 130,button
kartverket/kvib pull request #282
Opened 2023-06-19 11:38 UTC by elisekittelsby

# Beskrivelse
Kvibifisert Button med kartverkets design. Opprettet dokumentasjon for komponenten.

# Sjekkliste
- [ ] Sjekket at komponenten matcher designet i Figma
- [ ] Har fått design review med en designer
- [ ] Sjekket universell utforming for komponenten. Se for eksempel:
  - https://www.magentaa11y.com/web/
  - https://a11y-101.com/development
  - https://www.a11yproject.com/checklist/#appearance
- [ ] Denne PR-en inneholder en enkelt komponent

2023-06-19 11:54 UTC, SebastianPMaro requested changes
Sette ikoner virker ikke. Jeg mener colorScheme, size og variant ikke burde ha mulighet til å være undefined, heller bare sett en default prop for dem.
![image](https://github.com/kartverket/kvib/assets/122277136/1f530d41-3387-4774-a976-241f9c759a7c)
Jeg antar at dobbel stjerne er for å vise at komponenten er kvibifisert?

2023-06-20 10:43 UTC, nilben approved these changes
Bittelitt småpirk bare, men ser ellers veldig bra ut.

2023-06-20 10:43 UTC, nilben commented on apps/storybook/stories/components/button/Button.mdx
> +**Solid button (primary)** Brukes for den viktigste, ønsket eller avsluttende handling.\
Fint å ta med her at det som hovedregel aldri skal være mer enn 1 primary-button på en side.

2023-06-20 10:43 UTC, nilben commented on apps/storybook/stories/components/button/Button.stories.tsx
> +      description: "If true, the button will be disabled.",
Hvorfor er denne beskrivelsen på engelsk?

2023-06-20 10:43 UTC, nilben commented on apps/storybook/stories/components/button/Button.mdx
> +Et nettsidesett og et forvatlningsett. For løsninger som skal gå inn under eller oppfattes som kartverket.no, skal man bruke det grønne nettsidesettet.\
typo i forvaltningssett

2023-06-20 14:12 UTC, merged