Komp 47
kartverket/kvib pull request #297
Opened 2023-06-28 10:02 UTC by FarAhm1

# Beskrivelse

Lagt til Input komponent og Form validation.

# Sjekkliste

- [ ] Sjekket at komponenten matcher designet i Figma
- [ ] Har fått design review med en designer
- [ ] Sjekket universell utforming for komponenten. Se for eksempel:
  - https://www.magentaa11y.com/web/
  - https://a11y-101.com/development
  - https://www.a11yproject.com/checklist/#appearance
- [ ] Denne PR-en inneholder en enkelt komponent

2023-06-30 12:44 UTC, plusk reviewed
Har ikke sett i detalj, bare noen småkommentarer

2023-06-30 12:44 UTC, plusk commented on package.json
> +    "@chakra-ui/icons": "^2.0.19",
Ser ikke ut som at denne blir brukt noe sted, men ser uansett ut i andre pull requests her som at en annen løsning for ikoner skal brukes

```suggestion
```

2023-06-30 12:44 UTC, plusk commented on packages/react/src/input/index.ts
> +// export * from "./Input";
```suggestion
```
Kommentar gjør ingenting

2023-07-03 11:11 UTC, nilben requested changes
Rebase på siste versjon av master, og test at du får opp a11y, og hvordan dette fungerer. Savner også litt mer stories. Når du tester a11y ser du også litt mer hensikten med å ha flere stories, fremfor å bare bruke kontroll-panelet til å teste ulike states.

Ellers ser alt veldig bra ut!

2023-07-03 11:11 UTC, nilben commented on apps/storybook/stories/components/form-control/Form-control.stories.tsx
> +export const FormControl: FormControlStory = {
Jeg savner flere stories her (se https://kartverket.atlassian.net/wiki/spaces/TB/pages/616464426/Guidelines+for+bidragsl+ypa#%E2%9C%8F%EF%B8%8F--Dokumentere-komponenten%3A-eksempel-med-Link-komponent).

Du trenger ikke nødvendighvis en story for hver prop, men i hvert fall en egen story for invalid. Dette er viktig pga testing. Se også på hvordan Elise har satt opp dokumentasjonen for Button komponentet, for å få med blått ikon og pluss-tegn i venstre-menyen, og for å få en egen visning av hver story, med tilhørende a11y-testing. (rebase til siste versjon av master for å få med a11y).

2023-07-14 09:39 UTC, FarAhm1 commented
Oppretter ny PR på KOMP-134 branch med nyeste oppdateringer.

2023-07-14 09:39 UTC, closed without merging