Komp 159,buttonGroup
kartverket/kvib pull request #303
Opened 2023-06-30 06:02 UTC by elisekittelsby

# Beskrivelse
ButtonGroup-komponent er tilgjengelig med Kartverkets Design. Dokumentasjon er oppdatert.
Kritiske endringer:  
-**colorScheme** er lagt til med verdier: "green" (default), "blue", "gray", "red".

-bugfix: oppdatert colorScheme for Button til å ikke være required.

2023-07-03 08:28 UTC, SebastianPMaro requested changes
Kjmpekult 👍 Fant bare den ene små tingen å kommentere på.

2023-07-03 08:28 UTC, SebastianPMaro commented on packages/react/src/theme/components/index.ts
> +export { buttonTheme as Button } from "./button";
pirk, men kanskje vi burde la alle hete det samme, så jeg foreslår at du renamer den til default.

2023-07-04 07:42 UTC, SebastianPMaro approved these changes

2023-07-06 11:43 UTC, nilben approved these changes

2023-07-06 12:05 UTC, merged