KOMP-217-progress
kartverket/kvib pull request #398
Opened 2023-08-14 13:46 UTC by adrianflatner

# Beskrivelse

Legger til dokumentasjon for Progress.

<img width="1051" alt="Screenshot 2023-08-14 at 15 45 35" src="https://github.com/kartverket/kvib/assets/42931448/5a6f163a-86d6-4970-9036-ac3d1afa96a1">

# Sjekkliste

- [x] Sjekket universell utforming for komponenten. Se for eksempel:
  - https://www.magentaa11y.com/web/
  - https://a11y-101.com/development
  - https://www.a11yproject.com/checklist/#appearance
- [x] Denne PR-en inneholder en enkelt komponent

2023-08-15 06:44 UTC, nilben requested changes
Jeg ser du har feilende tester. Det skyldes at wcag krever at dette elementet blir brukt sammen med en label. I dokumentasjonen er vi jo opptatt av å vise selve elementet, og ikke labelen, men ta gjerne en titt på slider for å se på hvordan det er løst der.

2023-08-15 06:50 UTC, SebastianPMaro approved these changes

2023-08-15 06:50 UTC, SebastianPMaro commented on apps/storybook/stories/components/progress/Progress.stories.tsx
> +export const ProgressAnimated: Story = {
Du kan kanskje putte en isAnimated også under animert, men bortsett fra det ser det helt glimrende ut 😁

2023-08-15 07:40 UTC, adrianflatner commented
> Jeg ser du har feilende tester. Det skyldes at wcag krever at dette elementet blir brukt sammen med en label. I dokumentasjonen er vi jo opptatt av å vise selve elementet, og ikke labelen, men ta gjerne en titt på slider for å se på hvordan det er løst der.

Yes! Det hender jeg lager PRer uten at jeg har sjekket testene, men det fikses alltid😎 Jeg kan sørge for at jeg ikke lager PR før jeg har sjekket, så dere slipper å se på koden før den er helt ferdig😅

2023-08-21 06:52 UTC, nilben approved these changes

2023-08-21 11:18 UTC, merged