Samkjører standard fargetema på tvers av komponenter
kartverket/kvib pull request #405
Opened 2023-08-16 13:35 UTC by plusk

Prøvde å oppgradere kvib-versjonen min i nibas forleden, men møtte på en rekke problemer der halve applikasjonen ble grønn, mens den andre havlparten ble blå (altså sånn vi vil ha det i nibas). Nå følger ikke jeg veldig aktivt med på kvib, men det virker som at standardfargen som brukes på komponenter er grønn. Det er noe man kan sette sentralt for alle komponenter, så kan man eventuelt sette komponenter som skal være grå til å være det. Da blir det lettere for konsumenter å sette fargetemaet til sin applikasjon til å være f.eks. blå, fordi komponentene bare arver fargetema fra theme. Konsumenter og komponenter har enda all anledning til å overstyre fargetema, men med denne endringen slipper man å spesifikt si at alt skal være grønt eller blått eller hva nå enn.

Jeg prøvde å oppdatere dokumentasjon til å ikke spesifikt sette `colorScheme="green"` siden det uansett skjer av seg selv nå, slik at man ikke forvirrer brukeren til å tro at de alltid må gjøre det for å få en grønn knapp.

Noen ting å være obs på:

- Siden jeg satte standarden til å være grønn når den før var grå, så kan det godt være noen komponenter som _skulle_ være grå nå er grønn. Jeg tok utgangspunkt i dokumentasjonen for de forskjellige komponentene for å se hva tiltenkt default var. Hvis det er noe som ble feil så er det bare å rette det opp i theme/index, der vi sier hvilke komponenter som skal være grå.
- Jeg la merke til at det er ubrukte stiler i theme/components, de må videre-eksporteres i theme/components/index for å fungere. Det gjelder radio.ts og input.ts fra det jeg kan se.
- Prøv å unngå å tukle med colorscheme på komponentnivå med mindre man skal gjøre noe spesielt med det, det er veldig mye som allerede skjer av seg selv. F.eks. i Button.tsx ser jeg at dere har prøvd å få knapper til å arve fra buttongroup, men de gjør allerede det av seg selv, så annet enn typen trenger man ikke å nevne colorscheme.

2023-08-17 08:40 UTC, nilben approved these changes
Dette ser for meg ut som en bra forbedring, som vil gjøre det enklere både for brukerne og for designsystemteamet og få riktig fargetemaer.

2023-08-17 11:37 UTC, adrianflatner requested changes
Dette er helt konge! 

Det er visst noe rart med fargene på icon button som vi må se på før vi merger. 

<img width="164" alt="Screenshot 2023-08-17 at 13 36 25" src="https://github.com/kartverket/kvib/assets/42931448/83e15096-3313-415a-ab89-34954aad0758">

2023-08-17 14:04 UTC, plusk commented
Jeg ser på det atm, finner en del snodigheter. Ser ut som at Chakra ikke behandler IconButton som en egen komponent, men heller som en utvidelse av Button, så måten vi themer den får litt merkelige konsekvenser. Finner nok ut av det etterhvert

2023-08-18 07:26 UTC, adrianflatner approved these changes
Ey, der funker det bra👌

2023-08-18 10:02 UTC, merged