KOMP-230: Add footer
kartverket/kvib pull request #413
Opened 2023-08-18 12:37 UTC by magnram

# Beskrivelse

Mangler Kartverket-logo
<img width="652" alt="image" src="https://github.com/kartverket/kvib/assets/14547908/7239d13d-a977-4580-b328-7979c1be330a">

# Sjekkliste

- [ ] Sjekket at komponenten matcher designet i Figma
- [ ] Har fått design review med en designer
- [ ] Sjekket universell utforming for komponenten. Se for eksempel:
  - https://www.magentaa11y.com/web/
  - https://a11y-101.com/development
  - https://www.a11yproject.com/checklist/#appearance
- [ ] Denne PR-en inneholder en enkelt komponent

2023-08-21 07:59 UTC, nilben requested changes
I all hovedsak ser dette veldig bra ut, men jeg savner litt flere stories, som viser ulike tilstander footeren kan ha, minimum en som viser hvordan den ser ut når alle options er slått av. Fant også en gui-feil på mobilstørrelse: 
![bilde](https://github.com/kartverket/kvib/assets/32133041/3a1a94d4-2dca-4246-8170-3081bba8fb3e)

Vi jobber også med å få lagt inn logo i pakka, sånn at det kan legges til.

2023-08-21 12:07 UTC, magnram commented
> I all hovedsak ser dette veldig bra ut, men jeg savner litt flere stories, som viser ulike tilstander footeren kan ha, minimum en som viser hvordan den ser ut når alle options er slått av. Fant også en gui-feil på mobilstørrelse: ![bilde](https://user-images.githubusercontent.com/32133041/261957823-3a1a94d4-2dca-4246-8170-3081bba8fb3e.png)
> 
> Vi jobber også med å få lagt inn logo i pakka, sånn at det kan legges til.

Da har jeg rettet opp disse kommentarene @nilben 😊

2023-08-24 08:57 UTC, erlendst commented
Jeg tenker egentlig at den er fin som en første versjon uansett, siden den nå funker på mobil og har fått på logo. Jeg og Wanni driver å ser på et design nå, men den kan fint komme ut, så kan man iterere på den senere. Så den er hvertfall ✅ fra meg, men her må dere andre også si for/imot.

2023-08-25 06:13 UTC, SebastianPMaro commented
![image](https://github.com/kartverket/kvib/assets/122277136/5b78351c-2ed9-4920-9ecf-233dd72ebbe6)
Kanskje den burde ha et eget kapittel som heter sideelementer?

2023-08-25 06:46 UTC, nilben approved these changes
Bra jobba!

2023-08-25 07:49 UTC, merged