KVIB-80-bundleFonts
kartverket/kvib pull request #433
Opened 2023-08-28 09:04 UTC by adrianflatner

# Beskrivelse

KVIB bruker allerede en npm-pakke som blir oppdatert for Material Symbols. Det som står i dokumentasjon om å hente fra googles servere er bare en fix hvis det ikke funker. Det er bare Farhad sitt prosjekt som har hatt dette problemet. Mulish-fonten blir hentet gjennom fontsource, så det er allerede tipptopp. Gjør noen endringer: 

- Fjerner gammelt kall til google fonts som ikke brukes. Det er byttet ut med fontsource.
- Legger til material symbols type til ikoner så de blir typesikre. 
- Fjerner forslag om å bruke google api dersom ikoner ikke funker. Ikke hørt om noe mer enn Farhad som hadde dette problemet. Ingen grunn til at det skal være et problem heller ettersom ikonene kommer fra en npm-pakke.

2023-08-28 10:16 UTC, SebastianPMaro requested changes
Controls for icon i storiesa til icon/iconButton er annerledes enn på Button nå (dropdown vs string) idk hvilken er bedre, men jeg tror begge burde være like.

2023-08-28 11:27 UTC, adrianflatner commented
> Controls for icon i storiesa til icon/iconButton er annerledes enn på Button nå (dropdown vs string) idk hvilken er bedre, men jeg tror begge burde være like.

Done + litt cleanup på controls i icon.

2023-08-28 11:30 UTC, SebastianPMaro approved these changes
Kjempeflott 👍

2023-08-29 08:24 UTC, nilben approved these changes

2023-08-29 11:27 UTC, merged