Komp 167 icon button button groups fix
kartverket/kvib pull request #461
Opened 2023-09-10 12:59 UTC by FarAhm1

2023-09-11 06:19 UTC, SebastianPMaro approved these changes
Er det varianter som ødelegger ButtonGroup? Siden vi har gått tilbake til primary/secondary/tertiary/ghost, så hvis det ikke er det burde det nok forandres 🤘

2023-09-11 06:38 UTC, nilben requested changes
Gå igjennom og sørg for å bruke nye navn på button-variants hele veien, også i iconButton. Og pass på å ikke sette default-colorScheme. Ellers ser det bra ut!

2023-09-11 06:38 UTC, nilben commented on packages/react/src/button/IconButton.tsx
> +  variant?: "solid" | "outline" | "link" | "ghost";
Hvorfor går du tilbake på dette? Vi byttet navn med vilje, og har annonsert det til teamene, så vi bør ikke gå tilbake hvis vi kan unngå det

2023-09-11 06:38 UTC, nilben commented on packages/react/src/button/IconButton.tsx
> +  variant?: "solid" | "outline" | "link" | "ghost";
Ser det er brukt riktig navn i button.ts-fila :)

2023-09-11 06:38 UTC, nilben commented on packages/react/src/theme/components/iconButton.ts
>      colorScheme: "green",
Ser dette har ligget her fra før, men ikke sett default colorScheme her. Det er uansett satt til green for alle komponenter, så du trenger ikke sette det i det hele tatt så lenge det skal være grønn. Grunnen til at det ikke skal settes er for at det skla være lett å overskrive via prop i Kvib-providere.

2023-09-12 06:24 UTC, nilben approved these changes

2023-09-14 07:34 UTC, merged