Endre url fra /kvib til /designsystem
kartverket/kvib pull request #551
Opened 2023-10-12 08:17 UTC by SebastianPMaro

# Beskrivelse

Endre url fra /kvib til /designsystem

# Sjekkliste

- [ ] Sjekket at komponenten matcher designet i Figma
- [ ] Har fått design review med en designer
- [ ] Sjekket universell utforming for komponenten. Se for eksempel:
  - https://www.magentaa11y.com/web/
  - https://a11y-101.com/development
  - https://www.a11yproject.com/checklist/#appearance
- [ ] Denne PR-en inneholder en enkelt komponent

2023-10-12 08:47 UTC, adrianflatner commented
Et par ting til å endre😎
- manager-head.html (content)
- manager.js (title)
- theme.js (brandTitle)

2023-10-12 12:55 UTC, SebastianPMaro commented
![image](https://github.com/kartverket/kvib/assets/122277136/bf85fb07-a964-456a-b14a-5f774216094e)
Da jeg skiftet brandTitle, fant jeg noe litt viktig under.

2023-10-19 06:29 UTC, nilben requested changes
Se kommentarer i koden.

2023-10-19 06:29 UTC, adrianflatner commented on apps/storybook/stories/components/header/Header.stories.tsx
> +    logoLink: "https://kartverket.github.io/designsystem/",
Noen lenker har /kvib og andre har /designsystem

2023-10-20 06:27 UTC, nilben approved these changes

2023-10-20 07:03 UTC, merged