Vet ikke heelt hva mer jeg kan legge til.
kartverket/kvib pull request #614
Opened 2023-11-02 12:59 UTC by SebastianPMaro

# Beskrivelse

Jeg sitter litt fast på hva jeg kan finne på å putte i dokumentet. 

Jeg har sett på Fabric, Chakra og Spor for inspirasjon.

![image](https://github.com/kartverket/kvib/assets/122277136/3d39accb-f3f7-4ae2-9db0-99e77eabc4c7)

# Sjekkliste

- [ ] Sjekket at komponenten matcher designet i Figma
- [ ] Har fått design review med en designer
- [ ] Sjekket universell utforming for komponenten. Se for eksempel:
  - https://www.magentaa11y.com/web/
  - https://a11y-101.com/development
  - https://www.a11yproject.com/checklist/#appearance
- [ ] Denne PR-en inneholder en enkelt komponent

2023-11-02 15:01 UTC, adrianflatner commented
Ser ut som det ikke funker på previewen :(

2023-11-07 07:50 UTC, nilben requested changes

2023-11-07 07:50 UTC, nilben commented on apps/storybook/stories/components/data-display/badge/Badge.mdx
> +import { DocsHeading, DocsStoriesContainer, DocsStory } from "apps/storybook/stories/templates/index.ts"
Denne importen er feil. 

Adrian har en ny pull-request som snart skal merges her: https://github.com/kartverket/kvib/pull/618
Den inneholder blant annet en template som er fin å bruk, og har de riktige importene. Husk bare å merge inn master før du bruker den.

2023-11-07 09:15 UTC, nilben requested changes
Se kommentar i koden.

2023-11-07 11:48 UTC, SebastianPMaro commented
Virker nå 🐱‍👤

2023-11-07 14:46 UTC, adrianflatner commented
Vi trenger nok å fylle ut litt mer her✌️ Du kan fjerne overskrifter hvor det ikke er noe innhold også! Dvs. du kan fjerne "Kontekst", "Tilgjengelighet" og "Kjente feil". 

**Tilbakemelding på "Alternativer":**

Farge og hensikt er basically det samme. Så jeg tenker du kan fjerne "Farge" og bare ha "Hensikt". Så kan du skrive noe som: 

"Hensikten med Badge kan forsterkes med farger og varianter. Sterkere farger fanger blikket til brukeren og vil automatisk bli oppfattet som viktig. Derfor rangerer vi variantene `solid`, `subtle` og `outline` fra viktigst til mindre viktig." 

Så kan du gjøre eksempelet til noe som får vist fram farger og varianter i en kontekst. Endre til et enklere card som har flere badges med ulike farger og varianter for eksempel! 
 
Mvh 😶‍🌫️

2023-11-13 09:15 UTC, nilben approved these changes
Ser bra ut nå. Bare husk å ikke ta med tomme avsnitt.

2023-11-13 09:15 UTC, nilben commented on apps/storybook/stories/components/data-display/badge/Badge.mdx
> +<DocsHeading>Tilgjengelighet</DocsHeading>
Fjern denne overskriften, siden avsnittet er tomt.

2023-11-13 11:35 UTC, merged