komp-357-select
kartverket/kvib pull request #657
Opened 2023-11-21 14:21 UTC by adrianflatner

Endrer dokumentasjon for select i henhold til mal.

2023-11-23 07:51 UTC, nilben requested changes
Se kommentar om label, ellers ser det veldig bra ut!

2023-11-23 07:51 UTC, nilben commented on apps/storybook/stories/components/select/Select.mdx
> +      <Code>isRequired</Code>. Slik vil det også være enkelt å legge til en label. Dersom Select ikke brukes i form må en
Uavhengig av om select brukes i form eller ikke er det enkelt å legge til label, enten ved å bruke id på selecten og labelfor på label som referer til riktig ID, eller ved å wrappe selecten i labelen. Så det er kun i veldig spesielle tilfeller hvor man har en god grunn til å ikke ha synlig label at man skal bruke aria-label.

2023-11-23 07:51 UTC, nilben commented on apps/storybook/stories/components/select/Select.mdx
> +Select skal alltid ha en label. Dersom Select ikke brukes i form må en `aria-label` legges til for å tilfredsstille tilgjengelighetskrav.
Se linje 61.

2023-11-23 09:24 UTC, adrianflatner commented on apps/storybook/stories/components/select/Select.mdx
> +      <Code>isRequired</Code>. Slik vil det også være enkelt å legge til en label. Dersom Select ikke brukes i form må en
Ja, sant enig!

2023-11-24 07:38 UTC, nilben approved these changes

2023-11-24 08:45 UTC, merged