Komp 367 hooks
kartverket/kvib pull request #687
Opened 2023-12-20 01:12 UTC by FarAhm1

Added hooks documentation example.

2023-12-21 07:26 UTC, adrianflatner approved these changes
Disse ser veldig bra ut!

2024-01-05 09:18 UTC, nilben requested changes
Det meste ser veldig bra ut, men har lagt inn noen kommentarer på småting. Og så feiler test-runneren av en eller annen grunn.

2024-01-05 09:18 UTC, nilben commented on apps/storybook/stories/hooks/Theme.mdx
Dette er vel svaret på hvordan fikse komp-393 😄

2024-01-05 09:18 UTC, nilben commented on apps/storybook/stories/hooks/Theme.mdx
> +**useTheme** returnerer temaobjektet.
Her hadde det vært nice med en div som skifter farge avhengig av temaet eller noe slikt, bare for å vise litt mer hvordan dette fungerer.

2024-01-05 09:18 UTC, nilben commented on apps/storybook/stories/hooks/Theme.mdx
Evt er kanskje useToken enda enklere.

2024-01-12 07:58 UTC, nilben approved these changes

2024-01-12 08:09 UTC, merged