KOMP-403 Timepicker bugfix
kartverket/kvib pull request #706
Opened 2024-01-12 11:40 UTC by FarAhm1

Added colorScheme to Timepicker story examples.

2024-01-12 13:41 UTC, SebastianPMaro approved these changes
Kjempebra 👌 Quick & easy

2024-01-15 07:17 UTC, nilben requested changes
Dette holder dessverre ikke. Problemet er å sørge for at brukerne får riktig farge på komponenten uten å sette colorScheme explisitt. Det kan du teste ved å lage to stories med forskjellige decorators (https://storybook.js.org/docs/writing-stories/decorators). I preview.js finner du en decorator som sørger for at alle stories wrappes i KVIB-provideren (står litt om det her: https://design.kartverket.no/?path=/docs/info-oppsett--docs), den kan du også legge inn på en enkelt story, og velge grønt eller blått tema og sjekke at komponenten vises riktig. Les til og med "Endre default-farge" på forrige lenke, så ser du hvorfor dette er viktig.

Om du ikke finner ut av det, så kan du gjerne ringe meg på teams!

2024-01-25 08:11 UTC, SebastianPMaro approved these changes
Denne gangen ser det veldig bra ut. Testet i preview, og storiesa uten satt colorscheme hadde en default farge denne gangen. 👍

2024-02-06 08:23 UTC, nilben requested changes
Det nærmer seg veldig nå, men du skrifter fremdeles ikke farge basert på Kvib-provideren, sånn som det er beskrevet her: https://design.kartverket.no/?path=/docs/info-oppsett--docs#endre-default-farge

Jeg har laget en pull-request du kan se på, hvor det er lagt til to nye stories, som viser timepicker med provider som oppgir grønt og blått theme. Du må endre koden slik at storyen med blått theme får blå farge i komponenten, mens storyen med grønt theme beholder den grønne fargen.

2024-02-06 12:08 UTC, SebastianPMaro commented
> Det nærmer seg veldig nå, men du skrifter fremdeles ikke farge basert på Kvib-provideren, sånn som det er beskrevet her: https://design.kartverket.no/?path=/docs/info-oppsett--docs#endre-default-farge
> 
> Jeg har laget en pull-request du kan se på, hvor det er lagt til to nye stories, som viser timepicker med provider som oppgir grønt og blått theme. Du må endre koden slik at storyen med blått theme får blå farge i komponenten, mens storyen med grønt theme beholder den grønne fargen.

Det er bra du følger med bedre enn meg Bente 👏

2024-02-09 11:15 UTC, closed without merging